var res = {

    Add1_png:"res/gameAction/add1.png",
    Add2_png:"res/gameAction/add2.png",
    Allin1_png:"res/gameAction/allin1.png",
    Allin2_png:"res/gameAction/allin2.png",
    Bipai1_png:"res/gameAction/bipai1.png",
    Bipai2_png:"res/gameAction/bipai2.png",
    EnterRoom1_png:"res/gameAction/enterRoom1.png",
    EnterRoom2_png:"res/gameAction/enterRoom2.png",
    Follow1_png:"res/gameAction/follow1.png",
    Follow2_png:"res/gameAction/follow2.png",
    Open1_png:"res/gameAction/open1.png",
    Open2_png:"res/gameAction/open2.png",
    Ready1_png:"res/gameAction/ready1.png",
    Ready2_png:"res/gameAction/ready2.png",
    Throw1_png:"res/gameAction/throw1.png",
    Throw2_png:"res/gameAction/throw2.png",
    Time100_png:"res/gameAction/times100.png",
    Time300_png:"res/gameAction/times300.png",
    Time500_png:"res/gameAction/times500.png",
    Time800_png:"res/gameAction/times800.png",
    Time1000_png:"res/gameAction/times1000.png",


    Qiandao1_png:"res/activity/qiandao2.png",
    Qiandao2_png:"res/activity/qiandao2.png",
    Qiandao3_png:"res/activity/qiandao3.png",
    Yes1_png:"res/activity/yes1.png",
    Yes2_png:"res/activity/yes2.png",
    PrizeBg_png:"res/activity/prizeBg.png",
    Coins_png:"res/activity/coins.png",
    Task_png:"res/activity/lobby_task.png",

    LobbyCoin_png:"res/lobbyInfo/lobby_coin.png",
    LobbyDiamond_png:"res/lobbyInfo/lobby_diamond.png",
    Setting_png:"res/lobbyInfo/setting.png",
    Face_png:"res/lobbyInfo/face.png",
    LobbyCoin2_png:"res/lobbyInfo/lobby_coin_2.png",
    //LobbyDiamond2_png:"res/lobbyInfo/lobby_coin_2.png",
    Lobby_add1_png:"res/lobbyInfo/lobby_add_1.png",
    Lobby_add2_png:"res/lobbyInfo/lobby_add_2.png",
    Vip1_png:"res/lobbyInfo/vip1.png",
    Vip2_png:"res/lobbyInfo/vip2.png",
    Vip3_png:"res/lobbyInfo/vip3.png",
    Vip4_png:"res/lobbyInfo/vip4.png",
    Vip5_png:"res/lobbyInfo/vip5.png",
    Vip6_png:"res/lobbyInfo/vip6.png",
    Vip7_png:"res/lobbyInfo/vip7.png",
    Vip8_png:"res/lobbyInfo/vip8.png",
    DoubleCard_png:"res/lobbyInfo/doubleCard.png",
    ExChangeCard_png:"res/lobbyInfo/exchangeCard.png",
    ForbidCard_png:"res/lobbyInfo/forbidCard.png",
    Gender0_png:"res/lobbyInfo/gender0.png",
    Gender1_png:"res/lobbyInfo/gender1.png",
    Avatar_png:"res/lobbyInfo/avatar.png",
    AvatarBg_png:"res/lobbyInfo/avatarBg.png",
    DiamondToCoinBg_png:"res/lobbyInfo/diaToCoinBg.png",
    Arrow_png:"res/lobbyInfo/arrow.png",
    Pen_png:"res/lobbyInfo/pen.png",
    SigBg_png:"res/lobbyInfo/sigBg.png",
    GenderBox_png:"res/lobbyInfo/genderBox.png",
    GenderSelect_png:"res/lobbyInfo/genderSelect.png",

    Bg_png:"res/welcome/bg.png",
    Classic_png:"res/welcome/classic.png",
    CloseNormal_png : "res/welcome/CloseNormal.png",
    CloseSelected_png : "res/welcome/CloseSelected.png",

    UILoadingBar_png : "res/loadGame/loading.png",
    UILoadingBd_png : "res/loadGame/loadingbg.png",

    Game_png:"res/gameScene/gameBg.png",
    Back_png:"res/gameScene/back.png",

    //郭万福
    //新增加资源
    BackGround_jpg:"res/backGroundRes/back.jpg",
    //按钮资源
    GenDaoDi1_png:"res/an/GenDaoDi1.png",
    GenDaoDi2_png:"res/an/GenDaoDi2.png",
    GenDaoDi3_png:"res/an/GenDaoDi3.png",
    BiPaiString_png:"res/an/biPaiString.png",
    GenZhuString_png:"res/an/genZhuString.png",
    JiaZhuString_png:"res/an/jiaZhuString.png",
    KaiPaiString_png:"res/an/kaiPaiString.png",
    QiPaiString_png:"res/an/qiPaiString.png",
    QuanYaString_png:"res/an/quanYaString.png",
    ProhibitPicture_png:"res/an/prohibitPicture.png",
    OpenPicture_png:"res/an/openPicture.png",
    //角色图片资源
    Man_jpg:"res/player/man.jpg",
    Woman_jpg:"res/player/woman.jpg",
    MobileMy_jpg:"res/player/mobileMy.jpg",
    Mobile_jpg:"res/player/mobile.jpg",
    MoneyPicture_jpg:"res/player/moneyPicture.jpg",
    //扑克牌背面
    CardBack_png:"res/cards/back.png",
    //金币筹码图片资源
    Chips_Test_png:"res/chips/chips1.png",
    //玩家状态提示图片资源
    Abandon_png:"res/playerState/abandon.png",
    CheckCard_png:"res/playerState/checkCard.png",

    //比牌资源
    SelectBack_png:"res/compare/selectBack.png",
    Ring_png:"res/compare/ring.png",
    BiString_png:"res/compare/string.png",
    VsBack_png:"res/compare/vsBack.png",
    Vs_png:"res/compare/vs.png",
    BiPaiAnimation_plist:"res/compare/biPaiAnimation.plist",
    BiPaiAnimation_png:"res/compare/biPaiAnimation.png",
    LoserSprite_png:"res/compare/loserSprite.png",

    //跟注选择界面按钮资源
    Chips1_png:"res/follow/chips1.png",
    Chips2_png:"res/follow/chips2.png",
    Chips3_png:"res/follow/chips3.png",
    Chips4_png:"res/follow/chips4.png",
    Chips5_png:"res/follow/chips5.png",
    ChuJiString_png1:"res/follow/chuJiString1.png",
    ChuJiString_png2:"res/follow/chuJiString2.png",
    ChuJiString_png3:"res/follow/chuJiString3.png",
    ChuJiString_png4:"res/follow/chuJiString4.png",
    ChuJiString_png5:"res/follow/chuJiString5.png",
    ChipsProhibit_png:"res/follow/chipsProhibit.png",
    JiaZhuSprite:"res/follow/jiaZhuSprite.png",

    //定时器资源
    MyselfCounterTimer_png:"res/counterTimer/myselfCounterTimer.png",
    OtherCounterTimer_png:"res/counterTimer/otherCounterTimer.png",

    //游戏设置功能图片资源
    SettingButton_png:"res/setting/settingButton.png",
    SettingOpen_png:"res/setting/open.png",
    SettingClose_png:"res/setting/close.png",
    SettingBack_png:"res/setting/settingBack.png",
    SettingBack_closeButton_png:"res/setting/settingBack_closeButton.png",
    SettingBack_flowerLeft_png:"res/setting/settingBack_flowerLeft.png",
    SettingBack_flowerRight_png:"res/setting/settingBack_flowerRight.png",

    //返回按钮资源图片
    GameBack_png:"res/back/gameBack.png",
    GameBackPage_png:"res/back/gameBackPage.png",
    BackToGameHall_png:"res/back/backToGameHall.png",
    EnterOtherRoom_png:"res/back/enterOtherRoom.png",

    //聊天相关资源图片
    MenuComeInChat_png:"res/chat/menuComeInChat.png",
    ChatBackground_png:"res/chat/chatBackground.png",
    ChatItemBackGround_png:"res/chat/chatItemBackground.png",
    FaceItem1_png:"res/chat/faceItem1.png",
    FaceItem2_png:"res/chat/faceItem2.png",
    TackingItem1_png:"res/chat/tackingItem1.png",
    TackingItem2_png:"res/chat/tackingItem2.png",
    ChatHistoryItem1_png:"res/chat/chatHistoryItem1.png",
    ChatHistoryItem2_png:"res/chat/chatHistoryItem2.png",
    SendItem_png:"res/chat/sendItem.png",
    InputTxtBackground_png:"res/chat/inputTxtBackground.png",
    InputPicture_png:"res/chat/inputPicture.png",
    Line_png:"res/chat/line.png",
    Face1_png:"res/chat/face/1.png",
    Face2_png:"res/chat/face/2.png",
    Face3_png:"res/chat/face/3.png",
    Face4_png:"res/chat/face/4.png",
    Face5_png:"res/chat/face/5.png",
    Face6_png:"res/chat/face/6.png",
    Face7_png:"res/chat/face/7.png",
    Face8_png:"res/chat/face/8.png",
    Face9_png:"res/chat/face/9.png",
    Face10_png:"res/chat/face/10.png",
    Face11_png:"res/chat/face/11.png",
    Face12_png:"res/chat/face/12.png",
    Face13_png:"res/chat/face/13.png",
    Face14_png:"res/chat/face/14.png",
    Face15_png:"res/chat/face/15.png",
    Face16_png:"res/chat/face/16.png",
    Face17_png:"res/chat/face/17.png",

    //交互界面资源图片

    InteractionBackground_png:"res/interaction/interactionBackground.png",
    Back_flowerLeft_png:"res/interaction/back_flowerLeft.png",
    Back_flowerRight_png:"res/interaction/back_flowerRight.png",
    Close_png:"res/interaction/close.png",
    MyselfPhotoFrame_png:"res/interaction/myselfPhotoFrame.png",
    Boy_png:"res/interaction/boy.png",
    Girl_png:"res/interaction/girl.png",
    MoneyPicture_png:"res/interaction/moneyPicture.png",

    InteractionAnimation_plist:"res/interaction/interactionAnimation.plist",
    InteractionAnimation_png:"res/interaction/interactionAnimation.png",

    Flower_png:"res/interaction/flower.png",
    Cheers_png:"res/interaction/cheers.png",
    Kiss_png:"res/interaction/kiss.png",
    Egg_png:"res/interaction/egg.png",
    Shoe_png:"res/interaction/shoe.png",
    Bomb_png:"res/interaction/bomb.png",

    Gift_back_png:"res/interaction/gift_back.png",
    Gift_item1_png:"res/interaction/gift_item1.png",
    Gift_item2_png:"res/interaction/gift_item2.png",
    Gift_item3_png:"res/interaction/gift_item3.png",
    Gift_item4_png:"res/interaction/gift_item4.png",
    Gift_item5_png:"res/interaction/gift_item5.png",
    Gift_numberBack_png:"res/interaction/gift_numberBack.png",

    OtherMenu_png:"res/interaction/otherMenu.png",

    SendGiftSelectBackground_png:"res/interaction/sendGiftSelectBackground.png",

    //广播资源图片
    Horn_png:"res/radio/horn.png",
    DisplayTxtBoar_png:"res/radio/displayTxtBoar.png",
    RadioBackground_png:"res/radio/radioBackground1.png",
    TitleBoar_png:"res/radio/titleBoar.png",
    MenuBackground_png:"res/radio/menuBackground.png",
    MenuWorldString_png:"res/radio/menuWorldString.png",
    MenuFriendString_png:"res/radio/menuFriendString.png",
    MenuGongHuiString_png:"res/radio/menuGongHuiString.png",
    InputTxtBoarWorldChannel_png:"res/radio/inputTxtBoarWorldChannel.png",
    RadioSendItem_png:"res/radio/radioSendItem.png",

    //道具图片资源
    Ban_png:"res/prop/ban.png",
    Double_png:"res/prop/double.png",
    Exchange_png:"res/prop/exchange.png",
    PropForbid_png:"res/prop/propForbid.png",
    ExchangeCardWarnSprite_png:"res/prop/exchangeCardWarnSprite.png",

    //排行拍资源图片
    RankingMenu_png:"res/Ranking/RankingMenu.png",
    RankingMainBackground_png:"res/Ranking/MainBackground.png",
    Rank_select_menuBackground_png:"res/Ranking/rank_select_menuBackground.png",
    BackHallFromRank_png:"res/Ranking/backHallFromRank.png",
    Today_pay_png:"res/Ranking/today_pay.png",
    Yesterday_pay_png:"res/Ranking/yesterday_pay.png",
    Yesterday_comeIn_png:"res/Ranking/yesterday_comeIn.png",
    Money_rank_png:"res/Ranking/money_rank.png",
    Gift_rank_png:"res/Ranking/gift_rank.png",
    Rank_line_png:"res/Ranking/rank_line.png",
    Rank_warn_laBa_png:"res/Ranking/rank_warn_laBa.png",
    Rank_messageStore_png:"res/Ranking/rank_messageStore.png",
    Rank_messageHead_png:"res/Ranking/rank_messageHead.png",

    Rank_a_messageBackground_png:"res/Ranking/rank_a_messageBackground.png",
    Rank_no1_png:"res/Ranking/rank_no1.png",
    Rank_no2_png:"res/Ranking/rank_no2.png",
    Rank_no3_png:"res/Ranking/rank_no3.png",
    Rank_noOther_png:"res/Ranking/rank_noOther.png",
    Rank_man_png:"res/Ranking/rank_man.png",
    Rank_woMan_png:"res/Ranking/rank_woMan.png",
    Rank_photo_frame_png:"res/Ranking/rank_photo_frame.png",
    Rank_money_png:"res/Ranking/rank_money.png",
    Rank_myselfMessageMenu_png:"res/Ranking/rank_myselfMessageMenu.png",
    Rank_myselfMessagePayMenuString_png:"res/Ranking/rank_myselfMessagePayMenuString.png",
    Rank_myselfMessageStartMenuString_png:"res/Ranking/rank_myselfMessageStartMenuString.png",

    RankPersonalMain_png:"res/Ranking/rankingPersonalMessage/rankPersonalMain.png",
    RankClose_png:"res/Ranking/rankingPersonalMessage/close.png",
    RankBack_flowerLeft_png:"res/Ranking/rankingPersonalMessage/back_flowerLeft.png",
    RankBack_flowerRight_png:"res/Ranking/rankingPersonalMessage/back_flowerRight.png",
    RankMessageItemBackground_png:"res/Ranking/rankingPersonalMessage/messageItemBackground.png",
    Rank_man_jpg:"res/Ranking/rankingPersonalMessage/man.jpg",
    Rank_woMan_jpg:"res/Ranking/rankingPersonalMessage/woman.jpg",
    Rank_photoFrame_png:"res/Ranking/rankingPersonalMessage/myselfPhotoFrame.png",
    Rank_boy_png:"res/Ranking/rankingPersonalMessage/boy.png",
    Rank_girl_png:"res/Ranking/rankingPersonalMessage/girl.png",
    Rank_VIP1_png:"res/Ranking/rankingPersonalMessage/VIP1.png",
    Rank_VIP2_png:"res/Ranking/rankingPersonalMessage/VIP2.png",
    Rank_VIP3_png:"res/Ranking/rankingPersonalMessage/VIP3.png",
    Rank_VIP4_png:"res/Ranking/rankingPersonalMessage/VIP4.png",
    Rank_VIP5_png:"res/Ranking/rankingPersonalMessage/VIP5.png",
    Rank_VIP6_png:"res/Ranking/rankingPersonalMessage/VIP6.png",
    Rank_VIP7_png:"res/Ranking/rankingPersonalMessage/VIP7.png",
    Rank_VIP8_png:"res/Ranking/rankingPersonalMessage/VIP8.png",
    Rank_VIP9_png:"res/Ranking/rankingPersonalMessage/VIP9.png",
    Rank_moneyPicture_png:"res/Ranking/rankingPersonalMessage/Rank_moneyPicture.png",
    Rank_gift_back_png:"res/Ranking/rankingPersonalMessage/gift_back.png",
    Rank_gift_item1_png:"res/Ranking/rankingPersonalMessage/gift_item1.png",
    Rank_gift_item2_png:"res/Ranking/rankingPersonalMessage/gift_item2.png",
    Rank_gift_item3_png:"res/Ranking/rankingPersonalMessage/gift_item3.png",
    Rank_gift_item4_png:"res/Ranking/rankingPersonalMessage/gift_item4.png",
    Rank_gift_item5_png:"res/Ranking/rankingPersonalMessage/gift_item5.png",
    Rank_gift_numberBack_png:"res/Ranking/rankingPersonalMessage/gift_numberBack.png",
    Rank_otherMenu_png:"res/Ranking/rankingPersonalMessage/otherMenu.png",
    Rank_sendGiftSelectBackground_png:"res/Ranking/rankingPersonalMessage/sendGiftSelectBackground.png",

    //购买钻石选择界面资源
    BuyDiamond_buyDiamondBackground_png:"res/buyDiamondLayer/buyDiamondBackground.png",
    BuyDiamond_back_flowerLeft_png:"res/buyDiamondLayer/back_flowerLeft.png",
    BuyDiamond_back_flowerRight_png:"res/buyDiamondLayer/back_flowerRight.png",
    BuyDiamond_menuBackground_png:"res/buyDiamondLayer/menuBackground.png",
    BuyDiamond_line_horizontal_png:"res/buyDiamondLayer/line_horizontal.png",
    BuyDiamond_diamond_png:"res/buyDiamondLayer/diamond.png",
    BuyDiamond_faceValueMenu_png:"res/buyDiamondLayer/faceValueMenu.png",
    BuyDiamond_line_png:"res/buyDiamondLayer/line.png",


    //原有资源
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    Add1_png:"res/gameAction/add1.png",
    Add2_png:"res/gameAction/add2.png",
    Allin1_png:"res/gameAction/allin1.png",
    Allin2_png:"res/gameAction/allin2.png",
    Bipai1_png:"res/gameAction/bipai1.png",
    Bipai2_png:"res/gameAction/bipai2.png",
    EnterRoom1_png:"res/gameAction/enterRoom1.png",
    EnterRoom2_png:"res/gameAction/enterRoom2.png",
    Follow1_png:"res/gameAction/follow1.png",
    Follow2_png:"res/gameAction/follow2.png",
    Open1_png:"res/gameAction/open1.png",
    Open2_png:"res/gameAction/open2.png",
    Ready1_png:"res/gameAction/ready1.png",
    Ready2_png:"res/gameAction/ready2.png",
    Throw1_png:"res/gameAction/throw1.png",
    Throw2_png:"res/gameAction/throw2.png",
    Time100_png:"res/gameAction/times100.png",
    Time300_png:"res/gameAction/times300.png",
    Time500_png:"res/gameAction/times500.png",
    Time800_png:"res/gameAction/times800.png",
    Time1000_png:"res/gameAction/times1000.png",

    //music
    BackgroundMusic_ogg:"res/musicAndEffectSound/music/gameScene_backgroundMusic.ogg",
    Ttt:"res/musicAndEffectSound/effectSound/F_jidan.mp3"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}

var pomelo = window.pomelo;
var uid = "WuYanzu";
var rid = "rome1";
//var server_host = "127.0.0.1";
var server_host = "172.17.255.57";
//var server_host = "10.16.21.25";

